name : issagen
cmdname : issagen
summary : Issa Generator
description : Issa Generator
version : 1.1.0
changelog : Update
url : https://github.com/greymd/issagen
author : Yasuhiro, Yamada
email : yamada@gr3.ie
